// Deterministic, portable pseudo-randomness for procedural universe content.
//
// Every cell of space is generated by a pure function of its integer coordinates
// and the global seed, so revisiting a place always yields the same stars. All
// hashing uses 32-bit integer ops (Math.imul) which are bit-identical across
// browsers and Node — SplitMix64 would need BigInt and is slower; 32-bit murmur
// mixing is exact in JS doubles and plenty for visual generation.

const U32 = 0x100000000;

// murmur3 finalizer — avalanches a 32-bit accumulator into a well-mixed uint32.
function mix32(h) {
    h ^= h >>> 16; h = Math.imul(h, 0x85ebca6b);
    h ^= h >>> 13; h = Math.imul(h, 0xc2b2ae35);
    h ^= h >>> 16;
    return h >>> 0;
}

// murmur3 combine step — folds one 32-bit value into the accumulator.
function round32(h, k) {
    k = Math.imul(k | 0, 0xcc9e2d51);
    k = (k << 15) | (k >>> 17);
    k = Math.imul(k, 0x1b873593);
    h ^= k;
    h = (h << 13) | (h >>> 19);
    h = (Math.imul(h, 5) + 0xe6546b64) >>> 0;
    return h;
}

// Hash an arbitrary list of integers (seed, level, cell coords, index) → uint32.
// Values beyond 32 bits (e.g. a large global seed) fold their high word too.
export function hashInts(...vals) {
    let h = 0x9e3779b9 >>> 0;
    for (let i = 0; i < vals.length; i++) {
        const v = vals[i];
        h = round32(h, v | 0);
        // Fold the high word only for values that truly exceed 32 bits. Use
        // trunc (toward zero) so negative indices |v| < 2^32 give hi = 0 and
        // hash by their low word alone, matching the documented behaviour.
        const hi = Math.trunc(v / U32) | 0;
        if (hi !== 0) h = round32(h, hi);
    }
    return mix32(h ^ (vals.length >>> 0));
}

// mulberry32 — fast, decent-quality PRNG. Returns a function () → float in [0,1).
export function makeRNG(seed) {
    let a = seed >>> 0;
    return function () {
        a = (a + 0x6d2b79f5) >>> 0;
        let t = a;
        t = Math.imul(t ^ (t >>> 15), t | 1);
        t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
        return ((t ^ (t >>> 14)) >>> 0) / U32;
    };
}

// Inverse standard-normal CDF, Wichura's algorithm AS 241 (the double-
// precision "PPND16" rational-polynomial approximation; see Wichura 1988,
// Applied Statistics 37). The central region (|q| <= 0.425, ~85% of the
// mass) is a pure rational polynomial in q built only from +, -, *, / — the
// same operations Math.sqrt is defined to round exactly, so this branch is
// bit-identical on every IEEE-754 engine. The tail region (the remaining
// ~15%) needs sqrt(-log(r)) per the published algorithm: this is inherent to
// any accurate inverse-normal approximation (Acklam's and Moro's algorithms
// have the same shape) and can't be replaced by a further rational
// polynomial without giving up tail accuracy. Math.sin/Math.cos — the actual
// source of the old Box–Muller implementation's cross-engine drift — are
// gone entirely; Math.log only appears here, confined to the tail branch.
function invNorm(p) {
    const q = p - 0.5;
    if (Math.abs(q) <= 0.425) {
        const r = 0.180625 - q * q;
        return q * (((((((r * 2509.0809287301226727 +
                33430.575583588128105) * r + 67265.770927008700853) * r +
                45921.953931549871457) * r + 13731.693765509461125) * r +
                1971.5909503065514427) * r + 133.14166789178437745) * r +
                3.387132872796366608)
            / (((((((r * 5226.495278852854561 +
                28729.085735721942674) * r + 39307.89580009271061) * r +
                21213.794301586595867) * r + 5394.1960214247511077) * r +
                687.1870074920579083) * r + 42.313330701600911252) * r + 1.0);
    }
    let r = q < 0 ? p : 1 - p;
    r = Math.sqrt(-Math.log(r));
    let val;
    if (r <= 5.0) {
        r -= 1.6;
        val = (((((((r * 7.7454501427834140764e-4 +
                0.0227238449892691845833) * r + 0.24178072517745061177) * r +
                1.27045825245236838258) * r + 3.64784832476320460504) * r +
                5.7694972214606914055) * r + 4.6303378461565452959) * r +
                1.42343711074968357734)
            / (((((((r * 1.05075007164441684324e-9 +
                5.475938084995344946e-4) * r + 0.0151986665636164571966) * r +
                0.14810397642748007459) * r + 0.68976733498510000455) * r +
                1.6763848301838038494) * r + 2.05319162663775882187) * r + 1.0);
    } else {
        r -= 5.0;
        val = (((((((r * 2.01033439929228813265e-7 +
                2.71155556874348757815e-5) * r + 0.0012426609473880784386) * r +
                0.026532189526576123093) * r + 0.29656057182850489123) * r +
                1.7848265399172913358) * r + 5.4637849111641143699) * r +
                6.6579046435011037772)
            / (((((((r * 2.04426310338993978564e-15 +
                1.4215117583164458887e-7) * r + 1.8463183175100546818e-5) * r +
                7.868691311456132591e-4) * r + 0.0148753612908506148525) * r +
                0.13692988092273580531) * r + 0.59983220655588793769) * r + 1.0);
    }
    return q < 0 ? -val : val;
}

// rng() returns a float in [0, 1) quantized to 2^-32 buckets (mulberry32 is a
// 32-bit generator); invNorm is singular at p=0/1, so nudge each draw to the
// midpoint of its bucket — u = (raw + 0.5)/2^32 — landing strictly inside
// (0, 1) without ever touching either endpoint.
const HALF_ULP = 0.5 / U32;
function toOpenUnit(v) {
    return v + HALF_ULP;
}

// Standard normal deviate via AS 241 (one uniform draw per call).
export function randNormal(rng) {
    return invNorm(toOpenUnit(rng()));
}

// Derives a decorrelated 32-bit sub-seed from a seed + integer salt, so
// independent populations (binaries, kinematics, ...) can each get their own
// makeRNG stream without correlating with the parent stream or each other.
export function splitSeed(seed, salt) {
    return mix32(round32(seed >>> 0, salt | 0));
}

// Standard normal deviate via AS 241 (one uniform draw per call — no spare
// caching, so repeated calls against the same rng stream stay deterministic
// regardless of what other rng streams are doing between calls).
export function gaussian(rng) {
    return invNorm(toOpenUnit(rng()));
}

// Poisson sample: Knuth for small λ, Gaussian approximation for large λ.
export function samplePoisson(rng, lambda) {
    if (!(lambda > 0)) return 0;
    if (lambda < 30) {
        const L = Math.exp(-lambda);
        let k = 0, p = 1;
        do { k++; p *= rng(); } while (p > L);
        return k - 1;
    }
    const g = lambda + Math.sqrt(lambda) * randNormal(rng);
    return Math.max(0, Math.round(g));
}
