// Deterministic, portable pseudo-randomness for procedural universe content.
//
// Every cell of space is generated by a pure function of its integer coordinates
// and the global seed, so revisiting a place always yields the same stars. All
// hashing uses 32-bit integer ops (Math.imul) which are bit-identical across
// browsers and Node — SplitMix64 would need BigInt and is slower; 32-bit murmur
// mixing is exact in JS doubles and plenty for visual generation.

const U32 = 0x100000000;

// murmur3 finalizer — avalanches a 32-bit accumulator into a well-mixed uint32.
function mix32(h) {
    h ^= h >>> 16; h = Math.imul(h, 0x85ebca6b);
    h ^= h >>> 13; h = Math.imul(h, 0xc2b2ae35);
    h ^= h >>> 16;
    return h >>> 0;
}

// murmur3 combine step — folds one 32-bit value into the accumulator.
function round32(h, k) {
    k = Math.imul(k | 0, 0xcc9e2d51);
    k = (k << 15) | (k >>> 17);
    k = Math.imul(k, 0x1b873593);
    h ^= k;
    h = (h << 13) | (h >>> 19);
    h = (Math.imul(h, 5) + 0xe6546b64) >>> 0;
    return h;
}

// Hash an arbitrary list of integers (seed, level, cell coords, index) → uint32.
// Values beyond 32 bits (e.g. a large global seed) fold their high word too.
export function hashInts(...vals) {
    let h = 0x9e3779b9 >>> 0;
    for (let i = 0; i < vals.length; i++) {
        const v = vals[i];
        h = round32(h, v | 0);
        const hi = Math.floor(v / U32) | 0;
        if (hi !== 0) h = round32(h, hi);
    }
    return mix32(h ^ (vals.length >>> 0));
}

// mulberry32 — fast, decent-quality PRNG. Returns a function () → float in [0,1).
export function makeRNG(seed) {
    let a = seed >>> 0;
    return function () {
        a = (a + 0x6d2b79f5) >>> 0;
        let t = a;
        t = Math.imul(t ^ (t >>> 15), t | 1);
        t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
        return ((t ^ (t >>> 14)) >>> 0) / U32;
    };
}

// Standard normal deviate via Box–Muller.
export function randNormal(rng) {
    let u = 0, v = 0;
    while (u === 0) u = rng();
    while (v === 0) v = rng();
    return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
}

// Poisson sample: Knuth for small λ, Gaussian approximation for large λ.
export function samplePoisson(rng, lambda) {
    if (!(lambda > 0)) return 0;
    if (lambda < 30) {
        const L = Math.exp(-lambda);
        let k = 0, p = 1;
        do { k++; p *= rng(); } while (p > L);
        return k - 1;
    }
    const g = lambda + Math.sqrt(lambda) * randNormal(rng);
    return Math.max(0, Math.round(g));
}
